### ISSUE TITLE
Button para login

### ISSUE THREAD

**Issue by DanielHernandezGalvez** [SrDevDash/Game-of-Thrones-App#20]
Llama al backEnd para confirmar si estamos en la base de datos y nos devuelve una respuesta si fuimos encontrados o no, si fuimos encontrados nos manda a la landingPage

**Comment by SrDevDash** [comment]
### Si no encuentra al usuario va a lanzar una alerta con este mensaje

![image](https://user-images.githubusercontent.com/62898809/208993318-716ea316-cb50-4cea-b061-02df7678e65f.png)

## y si lo encuentra te mandara al home `/`
