### ISSUE TITLE
POST- Login (Create user)

### ISSUE THREAD

**Issue by SrDevDash** [SrDevDash/Game-of-Thrones-App#7]
### Se reciben los datos de usuarios del Front

se recibe ` { email: string, password: string }` (los filtros se hacen en el front, (se puede hacer doble check de verificación de datos para más seguridad, pero no lo haremos en este caso)) , luego de crear el usuario, se agrega en la lista de usuarios en el backend

**Comment by Siriusg2** [comment]
done

**Comment by SrDevDash** [comment]
@Siriusg2 hazle el push a tu rama xd
